// src/features/overlay-dropdown/TranscriptsList.svelte
<script lang="ts">
  import TranscriptResult from "$lib/components/TranscriptResult.svelte";
  import { transcriptionService } from "$lib/services/transcription.svelte";
  import ErrorMessage from "./ui/ErrorMessage.svelte";
</script>

<div class="flex h-full flex-col gap-2 overflow-y-auto py-3">
  {#if transcriptionService.error}
    <ErrorMessage error={transcriptionService.error} onClear={() => transcriptionService.clearError()} />
  {/if}

  {#if transcriptionService.liveResults.length === 0}
    <div class="flex h-full items-center justify-center text-(--text-muted)">
      No transcripts yet
    </div>
  {:else}
    {#each transcriptionService.liveResults as result (result.id)}
      <TranscriptResult transcript={result} />
    {/each}
  {/if}
</div>

// src/views/dashboard/tabs/ConversationsTab/components/TranscriptsList.vue
<script setup lang="ts">
import type { Transcript } from "@/types";
import TranscriptionCard from "@/components/TranscriptionCard.vue";

interface Props {
  transcripts: Transcript[];
  loading: boolean;
}

defineProps<Props>();
</script>

<template>
  <div class="flex flex-col gap-2">
    <div v-if="loading" class="text-center text-muted-foreground py-8">
      Loading transcripts...
    </div>
    <template v-else>
      <TranscriptionCard
        v-for="transcript in transcripts"
        :key="transcript.id"
        :transcript="transcript"
      />
      <div v-if="transcripts.length === 0" class="text-center text-muted-foreground py-8">
        No transcripts for this conversation
      </div>
    </template>
  </div>
</template>
