// src/components/ui/card/Card.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { cn } from "@/lib/utils"

const props = defineProps<{
  class?: HTMLAttributes["class"]
}>()
</script>

<template>
  <div
    data-slot="card"
    :class="
      cn(
        'text-card-foreground flex flex-col gap-6 rounded-xl border border-secondary/30 py-6 shadow-sm',
        props.class,
      )
    "
  >
    <slot />
  </div>
</template>

// src/lib/components/ui/Card.svelte
<script lang="ts">
  import { cn } from "$lib/utils";
  import type { HTMLAttributes } from "svelte/elements";

  let { class: className, children, ...rest }: HTMLAttributes<HTMLDivElement> = $props();
</script>

<div
  class={cn("rounded-(--radius) border border-(--color-border) bg-(--bg-card) p-4", className)}
  {...rest}
>
  {@render children?.()}
</div>
