// src/components/ui/input/Input.vue
<script setup lang="ts">
import type { HTMLAttributes } from "vue"
import { useVModel } from "@vueuse/core"
import { cn } from "@/lib/utils"

const props = defineProps<{
  defaultValue?: string | number
  modelValue?: string | number
  class?: HTMLAttributes["class"]
}>()

const emits = defineEmits<{
  (e: "update:modelValue", payload: string | number): void
}>()

const modelValue = useVModel(props, "modelValue", emits, {
  passive: true,
  defaultValue: props.defaultValue,
})
</script>

<template>
  <input
    v-model="modelValue"
    type="text"
    data-slot="input"
    :class="cn(
      'file:text-foreground placeholder:text-muted-foreground selection:bg-primary selection:text-primary-foreground dark:bg-input/30 border-primary/50 dark:border-input/80 flex h-9 w-full min-w-0 rounded-xl border bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none file:inline-flex file:h-7 file:border-0 file:bg-transparent file:text-sm file:font-medium disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 md:text-sm',
      'focus-visible:border-ring/60 focus-visible:ring-ring dark:focus-visible:ring-ring/60 focus-visible:ring-[2px]',
      'aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive',
      props.class,
    )"
    autoComplete="off"
    autoCorrect="off"
    autoCapitalize="off"
    :spellcheck="false"
  >
</template>

// src/lib/components/ui/Input.svelte
<script lang="ts">
  import { cn } from "$lib/utils";
  import { X } from "@lucide/svelte";
  import type { HTMLInputAttributes } from "svelte/elements";

  type Props = HTMLInputAttributes & {
    value?: string;
    showClearButton?: boolean;
  };

  let { value = $bindable(), class: className = "", showClearButton, ...rest }: Props = $props();

  let classes = $derived(
    cn(
      "w-full px-(--input-padding-x) py-(--input-padding-y) bg-(--input-bg) select-none",
      "border rounded-(--input-radius) border-(--input-border-color) hover:border-(--input-border-color-hover)",
      "text-base placeholder:text-(--text-muted) placeholder:font-semibold",
      "focus:outline-(length:--border-outline-width) focus:outline-(--input-border-color-focused) focus:outline-offset-0 focus:border-(--input-border-color-focused)",
      "disabled:opacity-60 disabled:cursor-not-allowed",
      className
    )
  );
</script>

<div class="relative w-full">
  <input bind:value class={classes} class:pr-9={showClearButton && value} {...rest} />
  {#if showClearButton && value}
    <button
      class={cn(
        "absolute inset-y-0 right-2.5 my-auto cursor-pointer rounded-(--radius)",
        "flex size-6 items-center justify-center",
        "text-(--text-muted) hover:bg-(--button-bg-secondary-hover) hover:text-(--text-primary)"
      )}
      onclick={() => (value = "")}
    >
      <X />
    </button>
  {/if}
</div>
