// src/features/conversation-list/ConversationList.svelte
<script lang="ts">
  import { Button, Loader } from "$lib/components/ui";
  import { useConversations } from "$lib/queries/conversations";
  import { cn } from "$lib/utils";
  import { Trash2 } from "@lucide/svelte";

  let {
    selectedId,
    onSelect,
    onDelete
  }: {
    selectedId: string | null;
    onSelect: (id: string) => void;
    onDelete: (id: string) => void;
  } = $props();

  const query = useConversations();

  function formatDate(value: string) {
    return new Intl.DateTimeFormat("en", {
      month: "short",
      day: "numeric",
      hour: "numeric",
      minute: "2-digit",
      hour12: false
    }).format(new Date(value));
  }
</script>

<div class="flex flex-col gap-1">
  {#if query.isLoading}
    <div class="flex items-center justify-center py-6">
      <Loader />
    </div>
  {:else if (query.data ?? []).length === 0}
    <div class="px-3 py-6 text-center text-sm text-(--text-muted)">No conversations yet</div>
  {:else}
    {#each query.data ?? [] as conversation (conversation.id)}
      <button
        class={cn(
          "group flex cursor-pointer items-center gap-2 rounded-(--radius) px-3 py-2 hover:bg-(--button-bg-secondary-hover)",
          conversation.id === selectedId && "bg-(--button-bg-secondary-hover)"
        )}
        onclick={() => onSelect(conversation.id)}
      >
        <div class="min-w-0 flex-1 text-start">
          <div class="truncate text-sm font-semibold">{conversation.title}</div>
          <div class="text-xs text-(--text-muted)">{formatDate(conversation.updated_at)}</div>
        </div>
        <Button
          variant="icon"
          class="shrink-0 opacity-0 group-hover:opacity-100"
          onclick={(event: MouseEvent) => {
            event.stopPropagation();
            onDelete(conversation.id);
          }}
        >
          <Trash2 class="size-4" />
        </Button>
      </button>
    {/each}
  {/if}
</div>

// src/views/dashboard/tabs/conversations/components/ConversationList.vue
<script setup lang="ts">
import { format } from "date-fns";
import { Trash2 } from "lucide-vue-next";
import { Button } from "@/components/ui/button";
import type { Conversation } from "@/types";

interface Props {
  conversations: Conversation[];
  selectedId: string | null;
}

defineProps<Props>();

const emit = defineEmits<{
  select: [conversation: Conversation];
  delete: [id: string];
}>();

function formatDate(timestamp: number) {
  return format(new Date(timestamp * 1000), "MMM d, HH:mm");
}
</script>

<template>
  <div class="w-64 shrink-0 border-r border-border flex flex-col overflow-hidden bg-card">
    <div class="flex-1 overflow-y-auto">
      <div
        v-for="conversation in conversations"
        :key="conversation.id"
        @click="emit('select', conversation)"
        class="group relative p-3 border-b border-border cursor-pointer hover:bg-accent transition-colors"
        :class="{ 'bg-accent': selectedId === conversation.id }"
      >
        <div class="text-sm text-foreground truncate pr-8">{{ conversation.title }}</div>
        <div class="text-xs text-muted-foreground mt-1">
          {{ formatDate(conversation.updatedAt) }}
        </div>
        <Button
            class="absolute right-2 top-1/2 -translate-y-1/2 opacity-0 group-hover:opacity-100"
            @click.stop="emit('delete', conversation.id)"
            variant="ghost"
            size="icon"
        >
            <Trash2 class="w-4 h-4 text-destructive-foreground" />
        </Button>
      </div>
      <div v-if="conversations.length === 0" class="p-3 text-sm text-muted-foreground">
        No conversations yet
      </div>
    </div>
  </div>
</template>
